version: "3.9"

services:

  backend:

    image: ecommerce_backend

    container_name: ecommerce_backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

    restart: always



  postgres:

    image: postgres:16

    container_name: ecommerce_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_backend

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    restart: always


volumes:
  postgres_data:
